create table if not exists public.poll_responses (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(trim(name)) between 1 and 80),
    choice text not null check (choice in ('B0FDB43VJL', 'B0H4PY63JC', 'B0H1LCQNMY', 'B0DD6XDN8T')),
    comment text not null default '' check (char_length(comment) <= 500),
    created_at timestamptz not null default now()
);

alter table public.poll_responses enable row level security;

grant select, insert on public.poll_responses to anon;
grant usage, select on sequence public.poll_responses_id_seq to anon;

drop policy if exists "Anyone can read poll responses" on public.poll_responses;
create policy "Anyone can read poll responses"
    on public.poll_responses for select to anon
    using (true);

drop policy if exists "Anyone can submit poll responses" on public.poll_responses;
create policy "Anyone can submit poll responses"
    on public.poll_responses for insert to anon
    with check (true);